@startuml

class User {
    - id:int
    - email:varchar
    - password:varchar
    - created_at:datetime
    - updated_at:datetime

    + regist_user():void
    + login():void
    + logout():void
}


class Result {
    - id:int
    - match_date:date
    - match_name:varchar
    - round:varchar
    - opponent_name:varchar
    - my_score:unsigned
    - opponent_score:unsigned
    - comment:varchar
    - created_at:datetime
    - updated_at:datetime
    - user_id:int

    + input_result(result:Result):void
    + search_result(opponent_name:varchar):Result
    + edit_result(result:Result):void
    + delete_result(result:Result):void
}

User "1" --- "0..*" Result

@enduml